### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [dangreenisrael/eslint-plugin-jest-formatting#107]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by benkimpel** [comment]
This is great. Left a note on your Draft PR. LMK if you need anything. Happy to help.

**Comment by dangreenisrael** [comment]
This is awesome!
