### ISSUE TITLE
Node engines is very specific

### ISSUE THREAD

**Issue by benkimpel** [dangreenisrael/eslint-plugin-jest-formatting#39]
Hello, @dangreenisrael. Thanks for writing this plugin. It's _exactly_ what I was looking for to correct some questionable style preferences from a certain member of my team. :laughing: :wink:

It seems like the `engines.node` value in `package.json` is perhaps overly specific. Any reason not to use `>= 8.10.0`?

When installing I had to use `yarn add --dev --ignore-engines eslint-plugin-jest-formatting`. (I'm on `8.16.0`) First time I've ever had to ignore-engines.

This isn't really a bug or anything. Just a question and a thank you.

**Comment by dangreenisrael** [comment]
Oversight. Nice catch!

**Comment by dangreenisrael** [comment]
Fixed in master https://github.com/dangreenisrael/eslint-plugin-jest-formatting/blob/182ab0f5330dc5c4cb9817119963ef6fdcc13517/package.json#L44

**Comment by benkimpel** [comment]
You're fast! TY
