### ISSUE TITLE
[BUG] Rules not properly marked as deprecated

### ISSUE THREAD

**Issue by dimitropoulos** [dangreenisrael/eslint-plugin-jest-formatting#75]
Eslint has an explicit mechanism for marking a rule as deprecated: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts#L295.

I maintain [eslint-config-intense](https://github.com/dimitropoulos/eslint-config-intense) which uses [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules) during upgrades of configs and plugins.  During a usage I noticed all the previous rules which are deprecated have not been marked as such.

> NOTE: Deprecated rules are found by looking at the metadata of the rule definition. All core rules and many plugin rules use this flag to indicate deprecated rules. But if you find a plugin that does not mark their rules as deprecated in the rule metadata, please file a pull request with that project.
> - eslint-find-rules readme.md

**Comment by dangreenisrael** [comment]
Thanks so much for reporting this @dimitropoulos. If you wanted to make a PR that would be super amazing, if not (I totally get it). I'll try to get a fix out ASAP.

Thanks again for reporting this!

**Comment by dangreenisrael** [comment]
Thanks so much for this @dimitropoulos.  I've merged your PR but there seems to be an issue in the deployment job. I will look into it tonight and try to have `v1.1.1` shipped by tomorrow.

**Comment by dangreenisrael** [comment]
@dimitropoulos v1.1.1 is deployed. Thanks again for your PR.
