### ISSUE TITLE
[BUG] Property "overrides" is the wrong type

### ISSUE THREAD

**Issue by moltar** [dangreenisrael/eslint-plugin-jest-formatting#78]
**Describe the bug**

After upgrading to 1.1.1, getting the following error:

```
Error: ESLint configuration in .eslintrc.js » plugin:jest-formatting/strict is invalid:
	- Property "overrides" is the wrong type (expected array but got `{"files":["**/*.test.*","**/*_test.*","**/*Test.*","**/*.spec.*","**/*_spec.*","**/*Spec.*","**/__tests__/*"],"rules":{"jest-formatting/padding-around-all":2}}`).
```

**To Reproduce**

Use 1.1.1 packaged as described in the docs.

**Expected behavior**

No errors.

**Screenshots**

N/A

**Desktop (please complete the following information):**

macOS

**Additional context**

N/A

**Comment by benkimpel** [comment]
Hey @moltar. Thanks for reporting this!

Could you let me know which version of ESLint you're on? I'm guessing from the error that you may be on ESLint 6.

If my guess is correct and if you need/want to get things working as soon as possible you could try running on ESLint 5.16.0 OR if that's not possible you could manually do the configuration that the configs are providing.

In ESLint 6 it looks like the overrides must be an array so for the real fix we'll need to address that in our configs [here](https://github.com/dangreenisrael/eslint-plugin-jest-formatting/blob/master/src/index.ts#L250) and [here](https://github.com/dangreenisrael/eslint-plugin-jest-formatting/blob/master/src/index.ts#L272) by wrapping those in arrays.

PRs are welcome!

**Comment by moltar** [comment]
```
❯ eslint -v
v6.6.0
```

> PRs are welcome!

So you are ok to migrating the config to ESLint 6? I guess it'd make it incompatible with 5 then?

**Comment by benkimpel** [comment]
I _think_ ESLint 5 can support both array and object versions of overrides, so I believe it's backwards compatible if we were to just switch to arrays. I'm not 100% sure, though. Lemme check release notes on ESLint.

**Comment by benkimpel** [comment]
Yeah, looks like we can just switch those over to arrays and be fine on ESLint 5, too. Not a problem if you're not looking to do a PR, btw. I'll be available to make the change this evening, but can't do so at the moment.

**Comment by moltar** [comment]
Thanks, Ben!

**Comment by benkimpel** [comment]
No problem. We'll still need to get a release out there. I think @dangreenisrael will bump package.json and tag this release in git.

**Comment by dangreenisrael** [comment]
@moltar @benkimpel The release is out

**Comment by benkimpel** [comment]
Thanks, @dangreenisrael

**Comment by benkimpel** [comment]
Checking back in... @moltar did this release (1.2.0) work out for you? How about for you @HosseinAgha and @Dreebo?

**Comment by Dreebo** [comment]
@benkimpel Thanks! Now everything is working

**Comment by benkimpel** [comment]
@Dreebo Thanks for checking back in! Glad to hear it's working.
