### ISSUE TITLE
[BUG] GitHub releases are maybe broken

### ISSUE THREAD

**Issue by moltar** [dangreenisrael/eslint-plugin-jest-formatting#79]
**Describe the bug**

Not sure what is causing this, but GitHub release page seems to be broken.

Doesn't have the descriptions.

And also, the last 3 releases are folded, and don't immediately stand out.

**To Reproduce**

Visit release page: https://github.com/dangreenisrael/eslint-plugin-jest-formatting/releases

**Expected behavior**

Each release has description and correct version.

**Screenshots**

![image](https://user-images.githubusercontent.com/491247/67637887-604def00-f8b5-11e9-9899-ead737f6f292.png)

**Desktop (please complete the following information):**

macOS

**Additional context**

N/A

**Comment by benkimpel** [comment]
Hrmmm. Interesting. I'm going to leave this one for @dangreenisrael. He is the release master.

**Comment by dangreenisrael** [comment]
On it

**Comment by dangreenisrael** [comment]
Thanks for pointing this out @moltar. I slipped a little with keeping them up to date. I've added the latest release in and will be better about keep them updated in the future.

Thanks again for bringing this to our attention.

**Comment by dangreenisrael** [comment]
https://github.com/dangreenisrael/eslint-plugin-jest-formatting/releases/tag/v1.1.1

**Comment by moltar** [comment]
Oh, so they are not automatic? Maybe something like semantic release would be beneficial?
