### ISSUE TITLE
[Rule] test name should be trimed

### ISSUE THREAD

**Issue by aymericbouzy** [dangreenisrael/eslint-plugin-jest-formatting#85]
I don't like when people leave white spaces at the beginning and end of tests. It's weird.

_Valid code example_

```JavaScript
it("is a valid test name", () => {
  // code
})
```

_Invalid code example_

```JavaScript
it(" is not a valid test name", () => {
  // code
})

it("is not valid either ", () => {
  // code
})
```

**Comment by benkimpel** [comment]
@aymericbouzy I haven't seen this one much in the wild, but I agree that's weird!! Seems like it could fall within the purview of this plugin.

**Comment by dangreenisrael** [comment]
👍 

@aymericbouzy Is this something you would be interested in taking on?

**Comment by aymericbouzy** [comment]
I've never written an ESlint rule before 😅  but I'm not afraid of trying 👍 Will keep you posted.

**Comment by aymericbouzy** [comment]
Ideally I would like an ESlint rule that corrects grammar mistakes in test names 😂 some of my interns are very creative with English ... just kidding it would be a nightmare without real benefit 😉

**Comment by benkimpel** [comment]
@aymericbouzy If you'd like any help or would like to bounce ideas or plans off someone just let me know. (This is probably a pretty good rule to start with!)

**Comment by erunion** [comment]
This case is already covered under the `valid-title` rule in [eslint-plugin-jest](https://www.npmjs.com/package/eslint-plugin-jest) for what it's worth.

https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/valid-title.md

**Comment by hockeybuggy** [comment]
Oh nice! Good catch @erunion . Looks like `valid-title` already exists and has a superset of the functionality described.

I am gonna close this to avoid duplicating effort. 😀

**Comment by benkimpel** [comment]
Nice! Thanks @erunion.

**Comment by dangreenisrael** [comment]
Thanks @erunion!
