### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [dangreenisrael/eslint-plugin-jest-formatting#88]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by benkimpel** [comment]
@MichaelDeBoey I haven't kept up to date on changes in ESLint 7. Do you know of any specific incompatibilities that we might run into here?

**Comment by MichaelDeBoey** [comment]
@benkimpel All changes can be found [here](https://eslint.org/blog/2020/05/eslint-v7.0.0-released#highlights) and [here](https://eslint.org/docs/user-guide/migrating-to-7.0.0).

**Comment by benkimpel** [comment]
Thanks @MichaelDeBoey. That's perfect. I'll evaluate our status this week... probably towards the end of the week. Lots going on at the moment!

**Comment by weyert** [comment]
Any way to progress this PR?

**Comment by MichaelDeBoey** [comment]
@weyert Like I said yesterday (https://github.com/dangreenisrael/eslint-plugin-jest-formatting/pull/89#issuecomment-647450593): #89 is good to be merged 🙂
