### ISSUE TITLE
[BUG] .nvmrc file needs an update

### ISSUE THREAD

**Issue by xiaoyunyang** [dangreenisrael/eslint-plugin-jest-formatting#97]
**Describe the bug**

The [.nvmrc](https://github.com/dangreenisrael/eslint-plugin-jest-formatting/blob/master/.nvmrc) file currently states `v8.10.0` but this causes the following error when running this project.

```
error eslint-plugin-jest-formatting@2.0.1: 
The engine "node" is incompatible with this module. 

Expected version "^10.12.0 || >=12.0.0". Got "8.10.0"
error Found incompatible module.
```

The fix is simple. Fix the node version in `.nvmrc`. But which version should be specified? 🤔

**To Reproduce**

1. clone this repo
2. run `yarn`

**Expected behavior**
No error should happen when you run `yarn`.

**Comment by benkimpel** [comment]
Hi @xiaoyunyang. Good catch. Thanks. I think I'd actually vote to remove that file all together. Any thoughts on it, @dangreenisrael?

**Comment by dangreenisrael** [comment]
Oh no! Great catch. I've got no problem with dropping `.nvmrc`.

@xiaoyunyang  Do you want to open a PR dropping it?

**Comment by benkimpel** [comment]
Deleting things is my favorite part of programming so I'm happy to do it if it comes down to it. But we should give @xiaoyunyang a chance in case their passion for deleting things is even greater than my own.

**Comment by dangreenisrael** [comment]
@benkimpel   Looks like @xiaoyunyang doesn't want it. Any interest in taking this on?

**Comment by benkimpel** [comment]
@dangreenisrael yeah, sounds good. I'll take care of it tomorrow morning.

**Comment by dangreenisrael** [comment]
Thanks @benkimpel
