### ISSUE TITLE
[BUG] `padding-around-expect-groups` wants space around `expect`s which are `await`ed

### ISSUE THREAD

**Issue by tmercswims** [dangreenisrael/eslint-plugin-jest-formatting#98]
**Describe the bug**
If I have two `expect`s right next to each other, and one of them is `await`ed, the `padding-around-expect-groups` rule wants there to be a blank line between them.

**To Reproduce**
Example code:
```ts
await expect(subject.asyncThingWhichThrows()).rejects.toThrow(SomeError);
expect(subject.thingWhichWorks()).toBe('some value');
```

**Expected behavior**
`await`ed `expect`s should be allowed to be right next to regular ones.

**Screenshots**
Real example:
![image](https://user-images.githubusercontent.com/1624639/116498994-ef97e200-a85f-11eb-82e2-d20b30e29c9b.png)

**Desktop (please complete the following information):**
- Windows 10
- Node 14
- ESLint 7.24
- plugin version 2.0.1

**Comment by dangreenisrael** [comment]
Nice catch @tmercswims.

Any interest in adding a test case and opening a PR to fix it?

**Comment by dangreenisrael** [comment]
Thanks so mych @tmercswims. I've just cut a 3.0.0 release with your improvements in it.

**Comment by tmercswims** [comment]
Of course, I'm happy that I could contribute! 🙂

**Comment by dangreenisrael** [comment]
Now we've got our hooks in you 😉
